FROM lupino/ardb-server
LABEL maintainer="yvictor"
LABEL maintainer.email="yvictor3141@gmail.com"


RUN sed -e 's/rocksdb.compaction.*/rocksdb.compaction OptimizeUniversalStyleCompaction/' \
        -i /etc/ardb.conf

EXPOSE 16379
ENTRYPOINT /usr/bin/ardb-server /etc/ardb.conf
