version: '3'
services:
  redis:
    image: redis:5-alpine
    volumes: 
        - /data/qc/redis:/data
    ports:
        - 6379:6379
    container_name: redis-qc
    restart: always
    networks:
      - backend 
      
  redis_monitor:
    image: redsmin/proxy
    environment:
      - REDIS_URI=redis://redis-qc:6379
      - REDSMIN_KEY=
    container_name: redis-redsmin-qc
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - redis
    restart: always
    networks:
      - backend
  
  
  
  qc:
    build:
      context: .
      dockerfile: Dockerfile
    image: qc:qc
    env_file: .env
    environment:
      - REDIS_HOST=redis-qc
      - REDIS_PORT=6379
      - REDIS_DBN=0
      - ARDB_HOST=ardb-qc
      - ARDB_PORT=16379
      - ARDB_DBN=0
      - LOG_LEVEL=INFO
      - LOG_FILE=qc.log
      - PYTHONUNBUFFERED=1
    volumes: 
        - ./:/opt/qc
        - /data/qc/redis:/data/redis
    container_name: qc-qc
    depends_on:
      - redis
    restart: always
    networks:
      - backend   
    

networks: 
  backend:
    driver: bridge
